# This is the SAM template that represents the architecture of your serverless application
# https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-template-basics.html

# The AWSTemplateFormatVersion identifies the capabilities of the template
# https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/format-version-structure.html
AWSTemplateFormatVersion: 2010-09-09
Description: >-
  Unruggable Gateways Lambda Example

# Transform section specifies one or more macros that AWS CloudFormation uses to process your template
# https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/transform-section-structure.html
Transform:
- AWS::Serverless-2016-10-31

Resources:
  gatewayFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/GatewayHandler.gatewayHandler
      CodeUri: .
      Runtime: nodejs20.x
      Events:
        ApiEvent:
          Type: Api
          Properties:
            RestApiId: !Ref GatewayApi
            Path: /
            Method: GET
      Architectures:
        - x86_64
      MemorySize: 128
      Timeout: 100
      Description: A Lambda function that serves Unruggable Gateways responses.
      Policies:
        # Give Lambda basic execution Permission to the GatewayHandler
        - AWSLambdaBasicExecutionRole

  GatewayApi:                         # API Gateway resource
    Type: AWS::Serverless::Api
    Properties:
      StageName: dev
